//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class included
    {
        public int included1 { get; set; }
        public Nullable<int> tour_id { get; set; }
        public Nullable<int> inclusion_id { get; set; }
        public Nullable<int> included_choice { get; set; }
        public string included_description { get; set; }
    
        public virtual inclusions inclusions { get; set; }
        public virtual tours tours { get; set; }
    }
}
