//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class itirerary
    {
        public int itinerary { get; set; }
        public Nullable<int> tour_id { get; set; }
        public Nullable<int> day_num { get; set; }
        public string itinerary_name { get; set; }
        public string itirarary_description { get; set; }
    
        public virtual tours tours { get; set; }
    }
}
