//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_rooms
    {
        public int order_room_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<int> room_count { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual rooms rooms { get; set; }
    }
}
