//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class programs
    {
        public int program_id { get; set; }
        public string program_name { get; set; }
        public string program_event { get; set; }
        public Nullable<System.DateTime> duration_begin { get; set; }
        public Nullable<System.DateTime> duration_end { get; set; }
    }
}
