//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_countries
    {
        public int tour_country_id { get; set; }
        public Nullable<int> tour_id { get; set; }
        public Nullable<int> country_id { get; set; }
    
        public virtual countries countries { get; set; }
        public virtual tours tours { get; set; }
    }
}
