//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewed_tours
    {
        public int viewed_tour_id { get; set; }
        public Nullable<int> tour_id { get; set; }
        public Nullable<int> account_id { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual tours tours { get; set; }
    }
}
